[package]
name = "proof-registry"
version = "0.1.0"
edition = "2024"

[dependencies]
casper-contract = "4"
casper-types = "4"

[features]
default = ["casper-contract/std", "casper-types/std"]

[[bin]]
name = "proof-registry"
path = "src/main.rs"
bench = false
doctest = false
test = false

[profile.release]
codegen-units = 1
lto = true
