[package]
name = "verifier-gate"
version = "0.1.0"
edition = "2024"

[dependencies]
casper-contract = "5.1"
casper-types = "6.0"

[features]
default = ["casper-contract/std", "casper-types/std"]

[[bin]]
name = "verifier-gate"
path = "src/main.rs"
bench = false
doctest = false
test = false

[profile.release]
codegen-units = 1
lto = true
