package sdk

import "time"

// Proof represents a ZK proof generated by the CasperProver.
type Proof struct {
	ID            string    `json:"id"`
	Type          string    `json:"type"` // e.g., "inference", "batch", "groth16", "stark"
	Data          string    `json:"data"` // Base64 encoded proof data
	Status        string    `json:"status"` // e.g., "pending", "verified", "failed"
	Timestamp     time.Time `json:"timestamp"`
	OnChainLink   string    `json:"on_chain_link,omitempty"`
	MerkleRoot    string    `json:"merkle_root,omitempty"`
	ModelID       string    `json:"model_id"`
	VerifierID    string    `json:"verifier_id,omitempty"` // ID of the verifier instance
	PublicInputs  string    `json:"public_inputs"` // Base64 encoded public inputs
	PrivateInputs string    `json:"private_inputs,omitempty"` // Hashed or encrypted private inputs
}

// Model represents an AI model registered with the CasperProver.
type Model struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Hash        string    `json:"hash"` // Content hash of the model (e.g., IPFS CID)
	Version     string    `json:"version"`
	ProofCount  int       `json:"proof_count"`
	RegisteredAt time.Time `json:"registered_at"`
	OwnerAddress string    `json:"owner_address"` // Casper address of the model owner
}

// BatchResult contains the outcome of a batch verification request.
type BatchResult struct {
	BatchID  string                       `json:"batch_id"`
	ProofIDs []string                     `json:"proof_ids"`
	Status   string                       `json:"status"` // e.g., "processing", "completed", "failed"
	Results  map[string]VerificationResult `json:"results"` // Individual results for each proof
}

// Challenge represents a challenge for proof aggregation or generation.
type Challenge struct {
	ID        string   `json:"id"`
	Type      string   `json:"type"` // e.g., "stark_aggregation", "groth16_proof_request"
	ProofIDs  []string `json:"proof_ids,omitempty"` // For aggregation challenges
	InputData string   `json:"input_data,omitempty"` // Base64 encoded input data for new proof generation
	ModelID   string   `json:"model_id,omitempty"` // Model to use for proof generation
}

// VerificationResult contains the outcome of a single proof verification.
type VerificationResult struct {
	ProofID    string    `json:"proof_id"`
	Status     string    `json:"status"` // e.g., "verified", "invalid", "error"
	Message    string    `json:"message"`
	VerifiedAt time.Time `json:"verified_at"`
	OnChainTx  string    `json:"on_chain_tx,omitempty"` // Transaction hash if verified on-chain
}

// PQCryptoStatus represents the current post-quantum cryptography readiness of the system.
type PQCryptoStatus struct {
	IsPqEnabled bool `json:"is_pq_enabled"`
	AvailableAlgorithms struct {
		SphincsPlus struct {
			IsEnabled      bool    `json:"is_enabled"`
			SecurityLevels []int   `json:"security_levels"` // NIST security levels (1-5)
			Details        string  `json:"details"`
		} `json:"sphincs_plus"`
		MlDsa struct {
			IsEnabled      bool    `json:"is_enabled"`
			SecurityLevels []int   `json:"security_levels"` // NIST security levels (1-5)
			Details        string  `json:"details"`
		} `json:"ml_dsa"`
	} `json:"available_algorithms"`
	HybridSignatureStatus struct {
		IsEnabled     bool   `json:"is_enabled"`
		CurrentScheme string `json:"current_scheme"`
		FallbackScheme string `json:"fallback_scheme"`
		Details       string `json:"details"`
	} `json:"hybrid_signature_status"`
	OverallSecurityLevel int       `json:"overall_security_level"` // Aggregate NIST security level
	LastUpdated          time.Time `json:"last_updated"`
}
